name: Test

on: [push, pull_request]


jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        optimize: [fast, safe, small]
        zig: [0.12.0, 0.13.0, master]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ matrix.zig }}
      - uses: actions/cache@v4
        with:
          path: ./.zig-cache
          key: build-cache-${{ matrix.os }}-${{ matrix.zig }}-${{ matrix.optimize }}
          restore-keys: |
            build-cache-${{ matrix.os }}-${{ matrix.zig }}-
            build-cache-${{ matrix.os }}
      - run: zig build test --release=${{ matrix.optimize }} --verbose --summary all --cache-dir ./.zig-cache --global-cache-dir ./.zig-cache --prominent-compile-errors
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - uses: actions/cache@v4
        with:
          path: ./zig-cache
          key: example-cache
          restore-keys: |
            build-cache-ubuntu-latest-master-
      - run: |
          zig fetch --save=datetime ../
          zig build run --verbose --summary all --cache-dir ./.zig-cache --global-cache-dir ./.zig-cache --prominent-compile-errors
        working-directory: ./example
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0
      - run: zig fmt --check .
